# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - run: dotnet build src/web-app/actions-hackathon.csproj

# I don't love this approach.  Ideally I would be able to set the message conditionally without needing to duplicate the steps. 
    - name: Publish Action C2D Message
      if: ${{ failure() }}
      uses: dcparsons/azure-iot-action@v1.0.2
      with:
        iot-hub-connection-string: ${{ secrets.IOT_HUB_CONNECTION_STRING }}
        device-id: ${{ secrets.IOT_DEVICE_NAME }}
        message: "failure"

    - name: Publish Action C2D Message
      if: ${{ success() }}
      uses: dcparsons/azure-iot-action@v1.0.2
      with:
        iot-hub-connection-string: ${{ secrets.IOT_HUB_CONNECTION_STRING }}
        device-id: ${{ secrets.IOT_DEVICE_NAME }}
        message: "success"
